---

driver:
  name: docker
  driver_config:
    ssl_verify_mode: ":verify_none"

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.13.37
  client_rb:
    ssl_verify_mode: ":verify_none"
  data_bags_path: "test/data_bags"
  encrypted_data_bag_secret_key_path: "test/data_bags/encrypted_data_bag_secret"
  roles_path: "test/roles"
  environments_path: "test/environments"

platforms:
  - name: centos-6.7
  - name: centos-7.2
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: base
    run_list:
      - role[base]
    includes: ["centos-6.7", "centos-7.2", "ubuntu-14.04", "ubuntu-16.04"]
    provisioner:
      client_rb:
        environment: "bonusbits_base"
    attributes:
      bonusbits_base:
        linux:
          selinux:
            configure: false
        firewall:
          configure: false
  - name: base_epel_repo
    run_list:
      - role[base]
    includes: ["centos-6.7", "centos-7.2"]
    provisioner:
      client_rb:
        environment: "bonusbits_base_epel_repo"
    attributes:
      bonusbits_base:
        linux:
          selinux:
            configure: false
        firewall:
          configure: false
  - name: base_no_software
    run_list:
      - role[base]
    includes: ["centos-6.7", "centos-7.2", "ubuntu-14.04", "ubuntu-16.04"]
    provisioner:
      client_rb:
        environment: "bonusbits_base_no_software"
    attributes:
      bonusbits_base:
        linux:
          selinux:
            configure: false
        firewall:
          configure: false
