AllCops:
  Exclude:
    - 'berks-cookbooks/**/*'
    - '.idea/**/*'
    - '.git/**/*'
    - '.kitchen/**/*'
    - '*.lock'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 60
  CountComments: false
  Enabled: true

#Style/FileName:
#  Enabled: false

Style/Encoding:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/EmptyLiteral:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

Documentation:
  Enabled: false

Style/CaseIndentation:
  # Valid values are: case, end
  IndentWhenRelativeTo: case
  IndentOneStep: true

#Style/CaseIndentation:
#  Description: 'Indentation of when in a case/when/[else/]end.'
#  StyleGuide: '#indent-when-to-case'
#  Enabled: true
